# Generated by Django 2.0.6 on 2018-06-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180612_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
